id: IAC94A595
legacy_id: P000546
ocr_import_info:
  bdrc_scan_id: W8LS16918
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T03:26:26'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-04T03:35:57.390283+00:00'
last_modified: 2022-09-04 11:40:26.475168
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W8LS16918
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW8LS16918
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། ཤེས་རབ་རྒྱལ་མཚན།
  author: མཉམ་མེད་ཤེས་རབ་རྒྱལ་མཚན།
statistics:
  ocr_word_mean_confidence_index: 0.8833976063673596
  ocr_word_median_confidence_index: 0.9599999785423279
quality: null
bases:
  I8LS16932:
    source_metadata:
      id: http://purl.bdrc.io/resource/I8LS16932
      total_pages: 1042
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I8LS16932.txt
    statistics:
      ocr_word_median_confidence_index: 0.949999988079071
      ocr_word_mean_confidence_index: 0.8564262927245178
    legacy_id: v004
  I8LS16931:
    source_metadata:
      id: http://purl.bdrc.io/resource/I8LS16931
      total_pages: 1196
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I8LS16931.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.8968905046290497
    legacy_id: v003
  I8LS16929:
    source_metadata:
      id: http://purl.bdrc.io/resource/I8LS16929
      total_pages: 1346
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I8LS16929.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.9119459706763876
    legacy_id: v001
  I8LS16933:
    source_metadata:
      id: http://purl.bdrc.io/resource/I8LS16933
      total_pages: 992
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I8LS16933.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.8922225509706362
    legacy_id: v005
  I8LS16934:
    source_metadata:
      id: http://purl.bdrc.io/resource/I8LS16934
      total_pages: 962
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I8LS16934.txt
    statistics:
      ocr_word_median_confidence_index: 0.9599999785423279
      ocr_word_mean_confidence_index: 0.8800617769703234
    legacy_id: v006
  I8LS16930:
    source_metadata:
      id: http://purl.bdrc.io/resource/I8LS16930
      total_pages: 1155
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I8LS16930.txt
    statistics:
      ocr_word_median_confidence_index: 0.9599999785423279
      ocr_word_mean_confidence_index: 0.8889666779891376
    legacy_id: v002
  I8LS16935:
    source_metadata:
      id: http://purl.bdrc.io/resource/I8LS16935
      total_pages: 1390
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I8LS16935.txt
    statistics:
      ocr_word_median_confidence_index: 0.9599999785423279
      ocr_word_mean_confidence_index: 0.8577575727446459
    legacy_id: v007
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
